stages:
  - check
  - test

flatpak:
  image: "quay.io/gnome_infrastructure/gnome-runtime-images:gnome-44"
  stage: test
  tags:
    - flatpak
  variables:
    BUNDLE: "flatsync-nightly.flatpak"
    MANIFEST_PATH: "build-aux/app.drey.FlatSync.Devel.json"
    FLATPAK_MODULE: "flatsync"
    APP_ID: "app.drey.FlatSync.Devel"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
  script:
    - flatpak install --user --noninteractive org.freedesktop.Sdk.Extension.llvm14//22.08
    - >
      xvfb-run -a -s "-screen 0 1024x768x24"
      flatpak-builder --keep-build-dirs --user --disable-rofiles-fuse flatpak_app --repo=repo ${BRANCH:+--default-branch=$BRANCH} ${MANIFEST_PATH}
    - flatpak build-bundle repo ${BUNDLE} --runtime-repo=${RUNTIME_REPO} ${APP_ID} ${BRANCH}
  artifacts:
    name: "Flatpak artifacts"
    expose_as: "Get Flatpak bundle here"
    when: "always"
    paths:
      - "${BUNDLE}"
      - ".flatpak-builder/build/${FLATPAK_MODULE}/_flatpak_build/meson-logs/meson-log.txt"
      - ".flatpak-builder/build/${FLATPAK_MODULE}/_flatpak_build/meson-logs/testlog.txt"
    expire_in: 14 days

clippy:
  image: "rust:alpine"
  stage: check
  script:
    - apk add flatpak-dev gtk4.0-dev musl-dev openssl-dev
    - rustup component add clippy
    - cargo clippy --all

rustfmt:
  image: "rust:slim"
  stage: check
  script:
    - rustup component add rustfmt
    # Create blank versions of our configured files
    # so rustfmt does not yell about non-existent files or completely empty files
    - echo -e "" >> src/config.rs
    - rustc -Vv && cargo -Vv
    - cargo fmt --version
    - cargo fmt --all -- --color=always --check
