[package]
name = "flatsync-daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["macros"]}
libflatpak = { version = "0.3.0", features = ["v1_13_3"] }
zbus = { version = "3.11.0", features = ["tokio"], default-features = false }
oo7 = { version = "0.1.0-beta.3", default-features = false, features = [
  "tokio",
  "native_crypto",
] }
serde_json = "1"
serde = "1"
surf = "2"
anyhow = "1"
thiserror = "1"
glib = "0.17"
libflatsync-common = { path = "../libflatsync-common" }
