[package]
name = "flatsync-daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libflatpak = { version = "0.3.0", features = ["v1_13_3"] }
zbus = "3.11.0"
